name: expense_and_net_worth_automation
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.2
  google_sign_in: ^6.0.2
  json_view: ^0.4.2
  shared_preferences: ^2.5.2
  file_picker: ^8.3.5
  url_launcher: ^6.3.1
  receive_sharing_intent: ^1.8.1
  syncfusion_flutter_pdf: ^31.2.18
  path_provider: ^2.1.5
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  launcher_name: ^1.0.2
  package_rename: ^1.8.0

package_rename_config:
  android:
    app_name: "Finance AL"
    package_name: "com.akshit.expense_and_net_worth_automation"

launcher_name:
  default: "Finance AL"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon3.jpg"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
